version: '3.4'

services:
  roobiq-db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=roobiq-database
    restart: always

  roobiq-server:
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    build:
      context: .
      dockerfile: roobiq-server/Dockerfile
    depends_on:
      - roobiq-db
      #- reverse-proxy-server
    restart: always
    environment:
      - BlogContext=Server=roobiq-db;Database=roobiq-database;Username=postgres;Password=admin;Port=5432
      - JWTSecretKey=bRhYJRlZvBj2vW4MrV5HVdPgIE6VMtCFB0kTtJ1m
      - JWTLifespan=2592000
    ports:
      - 5001:80

  #reverse-proxy-server:
    #image: nginx:latest
    #ports:
      #- 80:80
      #- 443:443
    #volumes:
      #- ./hosts:/etc/nginx/
    #restart: always