version: '3.4'

services:
  roobiq-db:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: roobiq-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=roobiq-database
    restart: always

  roobiq-server:
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    build:
      context: .
      dockerfile: roobiq-server/Dockerfile
    depends_on:
      - roobiq-db
      #- reverse-proxy-server
    restart: always
    ports:
      - "5000:80" 

  #reverse-proxy-server:
    #image: nginx:latest
    #ports:
      #- 80:80
    #volumes:
      #- ./hosts:/etc/nginx/
    #restart: always
