name: Build docker-file and push SSH

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: 185.91.55.155
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_user: root
        docker_compose_filename: docker-compose.override.yml